### ISSUE TITLE
Modpack crash by oreexcavator

### ISSUE THREAD

**Issue by fabri2000779** [IchigoGames/The-New-Fronter-Changelogs#1]
Modpack version: 23
when you veinmine a tree it crash, also this only happend on server not on SP, i recomend to think is change to Veinminer also this bug is reported to oreexcavator dev

**Comment by IchigoGames** [comment]
ya accept veinminer does not work at all anymore its not been updated in a long time but i think there is a update for oreexcavator so it should be fixed in v24 when it comes out.

**Comment by fabri2000779** [comment]
okay thanks for your fast answer anyway i reported to him https://github.com/Funwayguy/OreExcavation/issues/49

**Comment by IchigoGames** [comment]
OreExcavation-1.3.95 works in singeplayer anyway.

**Comment by Jo-Mamma75** [comment]
We run the 1.10.2 version of Veinminer (v0.35.3) in FoolCraft and have had no issues with it. Granted, the problem stated here is likely to do with 1.11.2 specifically but it may be something to reconsider and try in a dev version of the pack if the issue persists after v24.

**Comment by fabri2000779** [comment]
@IchigoGames it is nice that it works in SP but you need to think on the people that runs server, like me or @Jo-Mamma75 and alot of people more, the bug is pretty annoying because it crash the entire server, anyway the bug is reported hope that the mod dev can fix it and you could update your pack soon, thanks you

**Comment by IchigoGames** [comment]
ya i'm updating tomorrow and i just meant iv not tested multiplayer yet im about too.

**Comment by fabri2000779** [comment]
thanks you

**Comment by fabri2000779** [comment]
i got another bug for you haha this armour from armorplus
when you take it out from the inventory and put somewhere like anvil it disappears
and after a while it reappears in the inventory
so it cannot be removed from inventory
but after relog its fine

**Comment by fabri2000779** [comment]
and this one that i reported already to the mod dev https://github.com/MatrexsVigil/harvestcraft/issues/288
sorry if im annoying im just let you know the bugs that the people in my community find

**Comment by IchigoGames** [comment]
that one you reported to pams had reforged in it so i dont think it was pams

**Comment by IchigoGames** [comment]
the error said reforged anyway

**Comment by IchigoGames** [comment]
but fyi the issue with oreexcavator has been fixed i just have not updated the pack yet.

**Comment by fabri2000779** [comment]
okay thanks and sorry, i mean i reported to them because it happend with a machine of his mod
